In [ ]:
import numpy as np 
import array as array
np.__version__

List = [1 , 2, 3, 4, 5]
print(List) 

#creating an array using numpy 
array = np.array([1.23 , 3.4 , 3.14 ])
print(array)

# Arrays having different datatypes 
array2 = np.array([3.14 , 3  , 4 , 5, 6])
print(array2)

#to set the datatype explicitlyy in an array 
dTypeArray = np.array([1 , 2 , 3.14  ,  5 , 6 ] , dtype = 'float32')
print(dTypeArray)

#nested lists result in multidimensional arrays
mdArray = np.array([range(i , i+ 3) for i in [2 , 4, 6]])
print(mdArray)

# creating an array from scratch
zeroes = np.zeros(10 , dtype = int)
print(zeroes)

#creating a 4 * 3 array of int 
Ones = np.ones((4 , 3) , dtype = int )
print(Ones)

#to create a array with perticular number
full = np.full((3 , 5) , 4.5)
print(full)
# to create an array with random values

random = np.random.random((3 , 3))
print(random)

[1, 2, 3, 4, 5]
[1.23 3.4  3.14]
[3.14 3.   4.   5.   6.  ]
[1.   2.   3.14 5.   6.  ]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[0 0 0 0 0 0 0 0 0 0]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[4.5 4.5 4.5 4.5 4.5]
 [4.5 4.5 4.5 4.5 4.5]
 [4.5 4.5 4.5 4.5 4.5]]
[[0.34879695 0.76115722 0.52041039]
 [0.78959412 0.80477085 0.18733056]
 [0.71846605 0.7930424  0.39017982]]
